CREATE table If not exists Dealers(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Description Text NULL,
    ConcurrencyStamp VARCHAR(255) NULL,
);

CREATE TABLE IF NOT EXISTS Cars (
  Id        INTEGER PRIMARY KEY AUTOINCREMENT,
  DealerId  INTEGER NOT NULL,
  Make      TEXT    NOT NULL,
  Model     TEXT    NOT NULL,
  Year      INTEGER NOT NULL,
  Stock     INTEGER NOT NULL,
  ConcurrencyStamp VARCHAR(255) NULL,
  FOREIGN KEY (DealerId) REFERENCES Dealers(Id)
);


CREATE TABLE IF NOT EXISTS AspNetUsers(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    DealerId INTEGER NULL,
    UserName VARCHAR(255) NOT NULL UNIQUE,
    NormalizedUserName VARCHAR(255) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    NormalizedEmail VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    FOREIGN KEY (DealerId) REFERENCES Dealers(Id)
);


CREATE TABLE IF NOT EXISTS AspNetRoles(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    NormalizedName VARCHAR(255) NOT NULL,
    ConcurrencyStamp VARCHAR(255) NULL
);


CREATE TABLE IF NOT EXISTS AspNetUserRoles(
    UserId INTEGER NOT NULL,
    RoleId INTEGER NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id),
    FOREIGN KEY (RoleId) REFERENCES AspNetRoles(Id)
);


